"""Page-1 example (ra-01 #1784): one logged undefended attack run, replayed against the calibrated allowlist, whose
first refused call is the first harmful call. Row and refusal are read from the logs and the envelope, not typed.
Writes outputs/tables/example_replay.tex."""
import json
import os
import sys

os.environ["HOLDOUT_SET"] = "all48"
D = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.dirname(D)   # release root (code/ and data/ are siblings)
sys.path.insert(0, D)
sys.path.insert(0, f"{D}/analysis")
import m3_common as C          # noqa: E402
import m3_envelope as ME       # noqa: E402
import m3_select as MS         # noqa: E402
import harness                 # noqa: E402
from rq12 import sel_entry, holdout_violations  # noqa: E402

MODEL, SUITE, UT, IT, REP = "qwen3-8b-local", "slack", "user_task_1", "injection_task_4", 0


def tt(s):
    return "\\texttt{" + s.replace("_", "\\_").replace("{", "\\{").replace("}", "\\}") + "}"


e = sel_entry(MODEL, MS.PRIMARY_EPS)
v = next(r for r in holdout_violations(MODEL) if (r["suite"], r["ut"], r["it"], r["rep"]) == (SUITE, UT, IT, REP))
env = ME.build(ME.Pool(MODEL, False, k=e["k"]), SUITE, UT, exclude_tasks=C.HOLDOUT, **e["chosen"])
fb = ME.first_block(env, v["trace"])
assert fb is not None and env.violations(v["trace"][fb]["f"], dict(v["trace"][fb]["a"])) == ["<tool>"]
prompt = harness.suite(SUITE).user_tasks[UT].PROMPT
rows = []
for i, c in enumerate(v["trace"][: fb + 1], 1):
    a = c["a"]
    arg = ", ".join(f"{k}=" + (str(x)[:22] + ("..." if len(str(x)) > 22 else "")) for k, x in a.items())
    mark = "$\\times$" if i == fb + 1 else "\\checkmark"
    rows.append(f"{i} & {tt(c['f'])}({tt(arg)}) & {mark} \\\\")
body = "\n".join(rows)
os.makedirs(f"{ROOT}/outputs/tables", exist_ok=True)
open(f"{ROOT}/outputs/tables/example_replay.tex", "w").write(
    "% generated by analysis/make_example_fig.py\n\\begin{tabular}{@{}r@{\\ }p{0.80\\linewidth}@{\\ }c@{}}\n"
    f"\\multicolumn{{3}}{{@{{}}p{{0.97\\linewidth}}@{{}}}}{{Request: \\emph{{{prompt}}}}} \\\\\n\\midrule\n{body}\n\\end{{tabular}}\n")
print(open(f"{ROOT}/outputs/tables/example_replay.tex").read())
