"""Figures and tables for RQ1 / RQ2 from data/analysis_out/rq12.json (analysis/rq12.py). Writes outputs/figs/*.pdf
and outputs/tables/*.tex. RQ3 / RQ4 figures are added when their data land.
Usage: python3 analysis/make_figs.py"""
import json
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

D = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.dirname(D)   # release root (code/ and data/ are siblings)
FIG, TAB = f"{ROOT}/outputs/figs", f"{ROOT}/outputs/tables"
os.makedirs(FIG, exist_ok=True); os.makedirs(TAB, exist_ok=True)
NAME = {"qwen3-8b-local": "Qwen3-8B", "llama31-8b-local": "Llama-3.1-8B", "gpt-4o-mini-2024-07-18": "gpt-4o-mini",
        "gpt-4.1-mini-2025-04-14": "gpt-4.1-mini"}
COL = {"qwen3-8b-local": "#4C72B0", "llama31-8b-local": "#8C8C8C", "gpt-4o-mini-2024-07-18": "#DD8452",
       "gpt-4.1-mini-2025-04-14": "#55A868"}
plt.rcParams.update({"font.size": 9, "axes.spines.top": False, "axes.spines.right": False, "pdf.fonttype": 42})


def chain_label(c):
    r = "all" if c["r"] >= 1000 else str(c["r"])
    return f"exact\nr={r}" if c["level"] == "exact" else f"{c['level']}\nr=all"


def fig_rq1(rq):
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.6))
    for m, x in rq["rq1"].items():
        ch = x["chain"]
        xs = range(len(ch))
        axes[0].plot(xs, [c["cal_mean_loss"] for c in ch], marker="o", ms=3, color=COL[m], label=NAME[m])
        if ch[0]["holdout_recall"] is not None and ch[0]["holdout_n_viol"] > 0:
            axes[1].plot(xs, [c["holdout_recall"] for c in ch], marker="o", ms=3, color=COL[m], label=NAME[m])
    eps = float(rq["meta"]["primary_eps"])
    axes[0].axhline(eps, ls="--", lw=1, color="black")
    axes[0].text(0.1, eps + 0.01, r"$\varepsilon$", fontsize=9)
    labels = [chain_label(c) for c in next(iter(rq["rq1"].values()))["chain"]]
    for ax, yl in zip(axes, ("calibration loss ↓", "holdout flag rate ↑")):
        ax.set_xticks(range(len(labels)))
        ax.set_xticklabels(labels, fontsize=7)
        ax.set_ylabel(yl)
        ax.set_ylim(0, 1.0 if "flag" in yl else 0.4)
    axes[0].legend(frameon=False, fontsize=7)
    fig.tight_layout()
    fig.savefig(f"{FIG}/rq1_chain.pdf", bbox_inches="tight")


def fig_rq2(rq):
    pooled = rq["rq2"]["pooled_per_attacker_tool"]
    items = sorted(pooled.items(), key=lambda kv: kv[1]["n"])
    names = [k.replace("_", " ") for k, _ in items]
    inter = [v["intercepted"] for _, v in items]
    invis = [v["invisible"] for _, v in items]
    fig, ax = plt.subplots(figsize=(5.2, 2.8))
    ax.barh(names, inter, color="#55A868", hatch="//", edgecolor="black", linewidth=0.4, label="flagged")
    ax.barh(names, invis, left=inter, color="#C44E52", edgecolor="black", linewidth=0.4, label="inside the tool layer")
    ax.set_xlabel("violations, pooled over the three security models")
    ax.legend(frameon=False, fontsize=7, loc="lower right")
    fig.tight_layout()
    fig.savefig(f"{FIG}/rq2_attacker_tool.pdf", bbox_inches="tight")


def tab_rq2(rq):
    rows = []
    for m in ("qwen3-8b-local", "gpt-4o-mini-2024-07-18", "gpt-4.1-mini-2025-04-14"):
        x = rq["rq2"][m]
        rows.append(f"{NAME[m]} & {x['n_viol']} & {100 * x['intercepted'] / x['n_viol']:.1f} & "
                    f"{100 * x['invisible'] / x['n_viol']:.1f} \\\\")
    body = "\n".join(rows)
    open(f"{TAB}/rq2_models.tex", "w").write(
        "% generated by analysis/make_figs.py\n\\begin{tabular}{lrrr}\n\\toprule\n"
        "Model & Violations & Flagged (\\%) $\\uparrow$ & Inside the tool layer (\\%) $\\downarrow$ \\\\\n\\midrule\n"
        f"{body}\n\\bottomrule\n\\end{{tabular}}\n")


def tab_rq1(rq):
    def lab(c):
        r = "all" if c["r"] >= 1000 else str(c["r"])
        return f"{c['level']}, $r$={r}"
    rows = []
    for m, x in rq["rq1"].items():
        cells = []
        for eps in ("0.05", "0.1", "0.15"):
            c = x["chosen_by_eps"][eps]
            ok = x["feasible_by_eps"][eps]
            cells.append(lab(c) + ("" if ok else r"$^\dagger$"))
        rows.append(f"{NAME[m]} & " + " & ".join(cells) + r" \\")
    open(f"{TAB}/rq1_eps_grid.tex", "w").write(
        "% generated by analysis/make_figs.py\n\\begin{tabular}{llll}\n\\toprule\n"
        "Model & $\\varepsilon=0.05$ & $\\varepsilon=0.10$ & $\\varepsilon=0.15$ \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


ARM_NAME = {"amlp": "AMLP (ours)", "block_all": "block-all", "spotlighting": "spotlighting", "sandwich": "sandwich",
            "tool_filter": "tool filter", "pi_detector": "PI detector", "melon": "MELON", "tripwire": "TripWire",
            "progent": "Progent", "camel": "CaMeL", "agentsentry": "Agent-Sentry"}
SEC3 = ["qwen3-8b-local", "gpt-4o-mini-2024-07-18", "gpt-4.1-mini-2025-04-14"]


def fig_rq3(q):
    r3 = q["rq3"]
    fig, axes = plt.subplots(1, 3, figsize=(7.2, 2.7), sharey=True)
    for ax, m in zip(axes, SEC3):
        for arm, e in r3[m].items():
            if arm == "amlp_vs_tripwire" or e.get("block_rate") is None:
                continue
            x, y = 100 * e["benign_cost"], 100 * e["block_rate"]
            ours = arm == "amlp"
            ax.scatter(x, y, s=28 if ours else 16, color="#C44E52" if ours else "#4C72B0", zorder=3)
            ax.annotate(ARM_NAME[arm].replace(" (ours)", ""), (x, y), fontsize=6, xytext=(3, 2), textcoords="offset points")
        ax.axvline(0, lw=0.6, color="grey")
        ax.set_title(NAME[m], fontsize=8)
        ax.set_xlabel("benign cost (pp) ↓")
    axes[0].set_ylabel("interception (%) ↑")
    fig.tight_layout()
    fig.savefig(f"{FIG}/rq3_cost_vs_interception.pdf", bbox_inches="tight")


def tab_rq3(q):
    r3 = q["rq3"]
    order = ["amlp", "progent", "agentsentry", "camel", "melon", "tripwire", "tool_filter", "sandwich", "spotlighting",
             "pi_detector", "block_all"]
    mods = SEC3 + ["llama31-8b-local"]
    rows = []
    for arm in order:
        cells = []
        for m in mods:
            e = r3[m].get(arm)
            if e is None:
                cells += ["--"] if m == "llama31-8b-local" else ["--", "--"]
                continue
            if m != "llama31-8b-local":
                cells.append(f"{100 * e['block_rate']:.1f}" if e.get("block_rate") is not None else "--")
            cells.append(f"{100 * e['benign_cost']:+.1f}")
        name = ARM_NAME[arm]
        if arm == "amlp":
            name = r"\textbf{AMLP} (ours)"
            cells = [r"\textbf{" + c + "}" for c in cells]
        rows.append(name + " & " + " & ".join(cells) + r" \\")
    head = (r"\begin{tabular}{l" + "rr" * 3 + "r}\n\\toprule\n"
            r" & \multicolumn{2}{c}{Qwen3-8B} & \multicolumn{2}{c}{gpt-4o-mini} & \multicolumn{2}{c}{gpt-4.1-mini} & Llama-3.1-8B \\" + "\n"
            r"Defense & Int.\,$\uparrow$ & Cost\,$\downarrow$ & Int.\,$\uparrow$ & Cost\,$\downarrow$ & Int.\,$\uparrow$ & Cost\,$\downarrow$ & Cost\,$\downarrow$ \\" + "\n\\midrule\n")
    open(f"{TAB}/rq3_main.tex", "w").write("% generated by analysis/make_figs.py\n" + head + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def fig_rq4(q):
    po = q["rq4"]["poisoning"]
    fig, ax = plt.subplots(figsize=(3.4, 2.4))
    for m in SEC3:
        xs = [0.0, 0.01, 0.05, 0.10]
        ax.plot([100 * x for x in xs], [100 * (po[m][str(x)]["recall"] if x == 0.0 else po[m][str(x)]["recall_mean"]) for x in xs], marker="o", ms=3, color=COL[m], label=NAME[m])
    ax.set_xlabel("poisoned mining runs (%)")
    ax.set_ylabel("flag rate (%) ↑")
    ax.set_ylim(0, 45)
    ax.legend(frameon=False, fontsize=7)
    fig.tight_layout()
    fig.savefig(f"{FIG}/rq4_poisoning.pdf", bbox_inches="tight")


def tab_rq4(q):
    r4 = q["rq4"]
    rows = []
    for m, x in r4["paraphrase"].items():
        for arm in ("amlp", "progent"):
            e = x[arm]
            nm = r"\textbf{AMLP} (ours)" if arm == "amlp" else "Progent"
            rows.append(f"Paraphrase, {NAME[m]} & {nm} & {100 * e['cost_orig']:+.1f} & {100 * e['cost_para']:+.1f} & {100 * e['shift']:+.1f} \\\\")
    rq12 = json.load(open(f"{ROOT}/data/analysis_out/rq12.json"))["rq1"]
    own_fb = {m: next(c["holdout_fb"] for c in x["chain"] if c["level"] == "any" and c["r"] >= 1000) for m, x in rq12.items()}
    flag_rows = []
    for k, v in r4["transfer"].items():           # errata E3: transfer reports the false-block rate only
        a, b = k.split("->")
        rows.append(f"Mined on {NAME[a]} & on {NAME[b]} & {100 * own_fb[b]:.1f} & {100 * v['fb']:.1f} & "
                    f"{100 * (v['fb'] - own_fb[b]):+.1f} \\\\")
        base, rec = q["rq4"]["poisoning"][b]["0.0"]["recall"], v["recall"]
        flag_rows.append(f"{NAME[a]} & {NAME[b]} & " + (f"{100 * base:.1f}" if base is not None else "--") + " & "
                         + (f"{100 * rec:.1f}" if rec is not None else "--") + " \\\\")
    open(f"{TAB}/rq4_shift.tex", "w").write(
        "% generated by analysis/make_figs.py\n\\begin{tabular}{llrrr}\n\\toprule\n"
        "Condition & Defense or target & Original & Shifted & Shift \\\\\n\\midrule\n" + "\n".join(rows)
        + "\n\\bottomrule\n\\end{tabular}\n")
    open(f"{TAB}/rq4_transfer_flag.tex", "w").write(
        "% generated by analysis/make_figs.py (exploratory, appendix)\n\\begin{tabular}{llrr}\n\\toprule\n"
        "Mined on & Applied to & Own allowlist $\\uparrow$ & Transferred $\\uparrow$ \\\\\n\\midrule\n" + "\n".join(flag_rows)
        + "\n\\bottomrule\n\\end{tabular}\n")


def fig_transfer():
    sn = json.load(open(f"{ROOT}/data/analysis_out/seen_novel.json"))
    cv = json.load(open(f"{ROOT}/data/analysis_out/seen_novel_curve.json"))
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.6))
    ax = axes[0]
    sp = json.load(open(f"{ROOT}/data/analysis_out/seen_novel_pure.json"))
    pooled = dict(sn["pooled"]); pooled.update(sp["pooled"])
    meths = [("M2", "sequences\nmined"), ("M1a-pure", "arguments\nmined"), ("M1a", "arguments\n+request"),
             ("M1b-pure", "tools\nmined"), ("M1b", "tools\n+predicted")]
    for i, (mk, lab) in enumerate(meths):
        for off, st, col, hatch in ((-0.18, "seen", "#4C72B0", ""), (0.18, "novel", "#C44E52", "//")):
            ax.bar(i + off, 100 * pooled[f"{mk}_{st}_fb"], width=0.34, color=col, hatch=hatch, edgecolor="black",
                   linewidth=0.4, label=st if i == 0 else None)
    ax.set_xticks(range(len(meths))); ax.set_xticklabels([l for _, l in meths], fontsize=6)
    ax.set_ylabel("false-block rate (%) ↓"); ax.set_ylim(0, 100); ax.legend(frameon=False, fontsize=7)
    ax = axes[1]
    for mk, lab, col in (("M2", "pDFA", "#C44E52"), ("M1a", "AMLP exact", "#4C72B0")):
        ks = [1, 2, 4, 6, 7]; js = [2, 4, 6, 8]
        ax.plot(ks, [100 * cv["fb"][f"{mk}_seen{k}"]["point"] for k in ks], marker="o", ms=3, color=col, label=f"{lab}, seen: own traces")
        ax.plot(js, [100 * cv["fb"][f"{mk}_novel{j}"]["point"] for j in js], marker="s", ms=3, ls="--", color=col,
                label=f"{lab}, novel: traces per mined task")
    ax.set_xlabel("traces"); ax.set_ylabel("false-block rate (%) ↓"); ax.set_ylim(0, 100)
    ax.legend(frameon=False, fontsize=5.5, loc="lower left", bbox_to_anchor=(0.0, 0.12))
    fig.tight_layout()
    fig.savefig(f"{FIG}/rq_transfer.pdf", bbox_inches="tight")
    names = {"qwen3-8b-local": "Qwen3-8B", "llama31-8b-local": "Llama-3.1-8B", "gpt-4o-mini-2024-07-18": "gpt-4o-mini",
             "gpt-4.1-mini-2025-04-14": "gpt-4.1-mini"}
    rows = []
    for mod, x in sn["per_model"].items():
        rows.append(f"{names[mod]} & " + " & ".join(f"{100 * x[f'{mk}_{st}_fb']:.1f}" for mk in ("M2", "M1a", "M1b") for st in ("seen", "novel")) + r" \\")
    open(f"{TAB}/rq_transfer.tex", "w").write(
        "% generated by analysis/make_figs.py\n\\begin{tabular}{lrrrrrr}\n\\toprule\n"
        " & \\multicolumn{2}{c}{Call sequence (pDFA)} & \\multicolumn{2}{c}{Argument set (AMLP exact)} & \\multicolumn{2}{c}{Tool set (AMLP)} \\\\\n"
        "Model & Seen\\,$\\downarrow$ & Novel\\,$\\downarrow$ & Seen\\,$\\downarrow$ & Novel\\,$\\downarrow$ & Seen\\,$\\downarrow$ & Novel\\,$\\downarrow$ \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def tab_rq3_replay():
    """Replay comparison of tool-level policies on identical runs (plan.md §16/§18 replay, C3' judge rows)."""
    sn = json.load(open(f"{ROOT}/data/analysis_out/seen_novel.json"))["pooled"]
    sp = json.load(open(f"{ROOT}/data/analysis_out/seen_novel_pure.json"))["pooled"]
    jt = json.load(open(f"{ROOT}/data/m3/judge_tests.json"))
    rows = [("Tool layer of AMLP, mined and predicted", sn["M1b_novel_fb"], sn["M1b_novel_flag"]),
            ("Mined tools only", sp["M1b-pure_novel_fb"], sp["M1b-pure_novel_flag"]),
            ("Predicted tools only", sp["M1b-pred_novel_fb"], sp["M1b-pred_novel_flag"]),
            ("Progent", jt["c3prime_fb"]["fb_progent"], jt["recall_A2rev"]["recall_progent"])]
    body = "\n".join(f"{n} & {100 * fb:.1f} & {100 * fl:.1f} \\\\" for n, fb, fl in rows)
    open(f"{TAB}/rq3_replay.tex", "w").write(
        "% generated by analysis/make_figs.py\n\\begin{tabular}{lrr}\n\\toprule\n"
        "Policy & False-block rate (\\%) $\\downarrow$ & Flag rate (\\%) $\\uparrow$ \\\\\n\\midrule\n" + body
        + "\n\\bottomrule\n\\end{tabular}\n")


def tab_rq3_ci(q):
    r3 = q["rq3"]
    order = ["amlp", "progent", "agentsentry", "camel", "melon", "tripwire", "tool_filter", "sandwich", "spotlighting",
             "pi_detector", "block_all"]
    ci = lambda e, k: f"[{100 * e[k][0]:.1f}, {100 * e[k][1]:.1f}]" if e and e.get(k) else "--"   # noqa: E731
    rows = []
    for arm in order:
        cells = []
        for m in SEC3:
            e = r3[m].get(arm)
            cells += [ci(e, "block_rate_ci"), ci(e, "benign_cost_ci")]
        cells.append(ci(r3["llama31-8b-local"].get(arm), "benign_cost_ci"))
        nm = r"\textbf{AMLP} (ours)" if arm == "amlp" else ARM_NAME[arm]
        rows.append(nm + " & " + " & ".join(cells) + r" \\")
    head = (r"\begin{tabular}{l" + "rr" * 3 + "r}\n\\toprule\n"
            r" & \multicolumn{2}{c}{Qwen3-8B} & \multicolumn{2}{c}{gpt-4o-mini} & \multicolumn{2}{c}{gpt-4.1-mini} & Llama-3.1-8B \\" + "\n"
            r"Defense & Int.\,$\uparrow$ & Cost\,$\downarrow$ & Int.\,$\uparrow$ & Cost\,$\downarrow$ & Int.\,$\uparrow$ & Cost\,$\downarrow$ & Cost\,$\downarrow$ \\" + "\n\\midrule\n")
    open(f"{TAB}/rq3_ci.tex", "w").write("% generated by analysis/make_figs.py\n" + head + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def tab_rq1_chain(rq):
    rows = []
    for m, x in rq["rq1"].items():
        for c in x["chain"]:
            lv = c["level"]
            r = "all" if c["r"] >= 1000 else str(c["r"])
            rec = f"{100 * c['holdout_recall']:.1f}" if c["holdout_recall"] is not None else "--"
            rows.append(f"{NAME[m]} & {lv} & {r} & {100 * c['cal_mean_loss']:.1f} & {100 * c['cal_bound']:.1f} & "
                        f"{100 * c['holdout_fb']:.1f} & {rec} \\\\")
        rows.append("\\midrule")
    rows = rows[:-1]
    open(f"{TAB}/rq1_chain.tex", "w").write(
        "% generated by analysis/make_figs.py\n\\begin{tabular}{llrrrrr}\n\\toprule\n"
        "Model & Level & $r$ & Cal. loss $\\downarrow$ & Bound $\\downarrow$ & Holdout FB $\\downarrow$ & Flag rate $\\uparrow$ \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def tab_rq4_poison(q):
    po = q["rq4"]["poisoning"]
    rows = []
    for m in SEC3:
        cells = [f"{100 * po[m]['0.0']['recall']:.1f}"]
        for rho in ("0.01", "0.05", "0.1"):
            e = po[m][rho]
            cells.append(f"{100 * e['recall_mean']:.1f} [{100 * e['recall_min']:.1f}, {100 * e['recall_max']:.1f}]")
        rows.append(f"{NAME[m]} & " + " & ".join(cells) + " \\\\")
    open(f"{TAB}/rq4_poison.tex", "w").write(
        "% generated by analysis/make_figs.py\n\\begin{tabular}{lrrrr}\n\\toprule\n"
        "Model & $\\rho=0$ & $\\rho=0.01$ & $\\rho=0.05$ & $\\rho=0.10$ \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def tab_tests():
    t = json.load(open(f"{ROOT}/data/m3/judge_tests.json"))
    txt = open(f"{ROOT}/data/results_m3_analyze.txt").read()
    c1 = json.loads(txt[txt.index("{"): txt.rindex("}") + 1][: txt[txt.index("{"):].index("\n}") + 2])["C1"]
    rows = []
    for m in ("qwen3-8b-local", "llama31-8b-local", "gpt-4o-mini-2024-07-18", "gpt-4.1-mini-2025-04-14"):
        e = c1["per_model"][m]
        rows.append(f"{NAME[m]} & {e['n']} & {100 * e['drop']:+.1f} & [{100 * e['ci95'][0]:+.1f}, {100 * e['ci95'][1]:+.1f}] \\\\")
    rows.append("\\midrule")
    rows.append(f"Pooled & {c1['n_pairs']} & {100 * c1['drop_pooled']:+.1f} & [{100 * c1['ci95'][0]:+.1f}, {100 * c1['ci95'][1]:+.1f}] \\\\")
    open(f"{TAB}/tests_utility.tex", "w").write(
        "% generated by analysis/make_figs.py\n\\begin{tabular}{lrrr}\n\\toprule\n"
        "Model & Pairs & Utility drop (pp) $\\downarrow$ & 95\\% interval \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def tab_setup():
    import sys
    sys.path.insert(0, D)
    import m3_common as C
    cnt = {}
    for kind, path in (("mining", "mine"), ("holdout benign, undefended", "monitor")):
        cnt[kind] = sum(len(C.read_jsonl(C.rows_path(False, path, m))) for m in C.MODELS)
    on = 0
    for m in C.MODELS:
        for g in ("main", "camel", "agentsentry"):
            p = C.rows_path(False, "online", m, g)
            if os.path.exists(p):
                on += len({r["row_id"] for r in C.read_jsonl(p)})
    para = sum(len({r["row_id"] for r in C.read_jsonl(p)}) for p in
               [f"{ROOT}/data/m3/paraphrase_{m}.jsonl" for m in ("qwen3-8b-local", "gpt-4.1-mini-2025-04-14")])
    h = json.load(open(f"{D}/holdout_split.json"))
    rows = [f"Holdout / selection / calibration tasks & {len(C.HOLDOUT)} / {len(C.SELECTION)} / {len(C.CALIBRATION)} \\\\",
            f"Models & Qwen3-8B, Llama-3.1-8B, gpt-4o-mini, gpt-4.1-mini \\\\",
            f"Mining runs & {cnt['mining']:,} \\\\",
            f"Undefended benign holdout runs & {cnt['holdout benign, undefended']:,} \\\\",
            f"Online holdout runs, all arms & {on:,} \\\\",
            f"Paraphrase runs & {para:,} \\\\"]
    open(f"{TAB}/setup.tex", "w").write(
        "% generated by analysis/make_figs.py\n\\begin{tabular}{ll}\n\\toprule\n" + "\n".join(rows)
        + "\n\\bottomrule\n\\end{tabular}\n")


def main():
    os.makedirs(FIG, exist_ok=True)
    os.makedirs(TAB, exist_ok=True)
    rq = json.load(open(f"{ROOT}/data/analysis_out/rq12.json"))
    fig_rq1(rq)
    fig_rq2(rq)
    tab_rq2(rq)
    tab_rq1(rq)
    q = json.load(open(f"{ROOT}/data/analysis_out/rq34.json"))
    fig_rq3(q); tab_rq3(q); tab_rq3_ci(q); fig_rq4(q); tab_rq4(q); fig_transfer(); tab_rq3_replay()
    tab_rq1_chain(rq); tab_rq4_poison(q); tab_tests(); tab_setup()
    print("figs:", sorted(os.listdir(FIG)), "tables:", sorted(os.listdir(TAB)))


if __name__ == "__main__":
    main()
